(SELECT 'YOUNGEST' AS TYPE, NAME, BIRTHDAY
FROM (
    SELECT NAME, BIRTHDAY,
           DENSE_RANK() OVER (ORDER BY BIRTHDAY ASC) AS rnk
    FROM worker
) AS ranked_workers
WHERE rnk = 1)

UNION

(SELECT 'OLDEST' AS TYPE, NAME, BIRTHDAY
FROM (
    SELECT NAME, BIRTHDAY,
           DENSE_RANK() OVER (ORDER BY BIRTHDAY DESC) AS rnk
    FROM worker
) AS ranked_workers
WHERE rnk = 1);
