SELECT 
    p.ID AS PROJECT_ID,
    SUM(w.SALARY * TIMESTAMPDIFF(MONTH, p.START_DATE, p.FINISH_DATE)) AS PRICE
FROM 
    project p
JOIN 
    worker w ON w.ID = p.ID
GROUP BY 
    p.ID
ORDER BY 
    PRICE DESC;
